apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: simple-example
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
  selector:
    app: devops-app
