apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devops-deployment
  namespace: simple-example
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: app
          image: jeanpsv/devops-days-bh-kubernetes-introduction:v1
          imagePullPolicy: Always
          command: ["npm", "start"]
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /ready
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /alive
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          env:
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SECRET_KEY
              value: "this-awesome-key-is-mine"
            - name: PORT
              value: "4000"
