apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: full-example
spec:
  type: LoadBalancer # can be LoadBalancer, ClusterIP or NodePort
  ports:
    - name: http # named port
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: devops-app
